package kw.test.model.admin;

import io.jboot.db.annotation.Table;
import kw.test.model.base.BaseAdmin;

/**
 * Generated by Jboot.
 */
@Table(tableName = "admin", primaryKey = "id")
public class Admin extends BaseAdmin<Admin> {
	
}
