package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseCommodityInfo;
import io.jboot.db.annotation.Table;
/**
 * Generated by Jboot.
 */
@Table(tableName = "commodity_info", primaryKey = "commodity_id")
public class CommodityInfo extends BaseCommodityInfo<CommodityInfo> {

	public Page<CommodityInfo> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
