package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseInstitutionCategory;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "institution_category", primaryKey = "institution_category_id")
public class InstitutionCategory extends BaseInstitutionCategory<InstitutionCategory> {

	public Page<InstitutionCategory> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
