package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseInstitutionInfo;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "institution_info", primaryKey = "institution_id")
public class InstitutionInfo extends BaseInstitutionInfo<InstitutionInfo> {

	public Page<InstitutionInfo> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
