package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BaseOrderAppendix;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "order_appendix", primaryKey = "appendix_id")
public class OrderAppendix extends BaseOrderAppendix<OrderAppendix> {
	
}
