package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BasePaymentBill;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "payment_bill", primaryKey = "payment_id")
public class PaymentBill extends BasePaymentBill<PaymentBill> {
	
}
