package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BasePurchasingOrder;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "purchasing_order", primaryKey = "purchasing_order_id")
public class PurchasingOrder extends BasePurchasingOrder<PurchasingOrder> {
	
}
