package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseStaffCategory;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "staff_category", primaryKey = "staff_category_id")
public class StaffCategory extends BaseStaffCategory<StaffCategory> {

	public Page<StaffCategory> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
