package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseSupplierInfo;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "supplier_info", primaryKey = "supplier_id")
public class SupplierInfo extends BaseSupplierInfo<SupplierInfo> {

	public Page<SupplierInfo> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
