package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseUserInfo;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
public class UserInfo extends BaseUserInfo<UserInfo> {

	public Page<UserInfo> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
