package io.jboot.admin.service.entity.model;

import com.jfinal.plugin.activerecord.Page;

import io.jboot.admin.service.entity.model.base.BaseWaregouseCategory;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "waregouse_category", primaryKey = "waregouse_category_id")
public class WaregouseCategory extends BaseWaregouseCategory<WaregouseCategory> {

	public Page<WaregouseCategory> paginate(int pageNumber, int pageSize) {
		// TODO Auto-generated method stub
		return null;
	}
	
}
