package io.jboot.admin.service.entity.model;


import io.jboot.admin.service.entity.model.base.BaseWarehouseInfo;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "warehouse_info", primaryKey = "waregouse_id")
public class WarehouseInfo extends BaseWarehouseInfo<WarehouseInfo> {
	
}
