package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BaseWaregouseInto;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "waregouse_into", primaryKey = "waregouse_id")
public class WaregouseInto extends BaseWaregouseInto<WaregouseInto> {
	
}
