package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWarehouseInfo<M extends BaseWarehouseInfo<M>> extends JbootModel<M> implements IBean {

	public void setWaregouseId(java.lang.String waregouseId) {
		set("waregouse_id", waregouseId);
	}
	
	public java.lang.String getWaregouseId() {
		return getStr("waregouse_id");
	}

	public void setWaregouseCategoryId(java.lang.String waregouseCategoryId) {
		set("waregouse_category_id", waregouseCategoryId);
	}
	
	public java.lang.String getWaregouseCategoryId() {
		return getStr("waregouse_category_id");
	}

	public void setWaregouseName(java.lang.String waregouseName) {
		set("waregouse_name", waregouseName);
	}
	
	public java.lang.String getWaregouseName() {
		return getStr("waregouse_name");
	}

	public void setWaregouseType(java.lang.String waregouseType) {
		set("waregouse_type", waregouseType);
	}
	
	public java.lang.String getWaregouseType() {
		return getStr("waregouse_type");
	}

	public void setWaregouseLead(java.lang.String waregouseLead) {
		set("waregouse_lead", waregouseLead);
	}
	
	public java.lang.String getWaregouseLead() {
		return getStr("waregouse_lead");
	}

	public void setWaregouseRemark(java.lang.String waregouseRemark) {
		set("waregouse_remark", waregouseRemark);
	}
	
	public java.lang.String getWaregouseRemark() {
		return getStr("waregouse_remark");
	}

}
