package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommodityInfo<M extends BaseCommodityInfo<M>> extends JbootModel<M> implements IBean {

	public void setCommodityId(java.lang.String commodityId) {
		set("commodity_id", commodityId);
	}
	
	public java.lang.String getCommodityId() {
		return getStr("commodity_id");
	}

	public void setSupplierId(java.lang.String supplierId) {
		set("supplier_id", supplierId);
	}
	
	public java.lang.String getSupplierId() {
		return getStr("supplier_id");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setCommodityType(java.lang.String commodityType) {
		set("commodity_type", commodityType);
	}
	
	public java.lang.String getCommodityType() {
		return getStr("commodity_type");
	}

	public void setCommodityUnitPrice(java.math.BigDecimal commodityUnitPrice) {
		set("commodity_unit_price", commodityUnitPrice);
	}
	
	public java.math.BigDecimal getCommodityUnitPrice() {
		return get("commodity_unit_price");
	}

	public void setCommodityProductionAddress(java.lang.String commodityProductionAddress) {
		set("commodity_production_address", commodityProductionAddress);
	}
	
	public java.lang.String getCommodityProductionAddress() {
		return getStr("commodity_production_address");
	}

}
