package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchasingOrder<M extends BasePurchasingOrder<M>> extends JbootModel<M> implements IBean {

	public void setPurchasingOrderId(java.lang.String purchasingOrderId) {
		set("purchasing_order_id", purchasingOrderId);
	}
	
	public java.lang.String getPurchasingOrderId() {
		return getStr("purchasing_order_id");
	}

	public void setCommodityId(java.lang.String commodityId) {
		set("commodity_id", commodityId);
	}
	
	public java.lang.String getCommodityId() {
		return getStr("commodity_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setSupplierInfo(java.lang.String supplierInfo) {
		set("supplier_info", supplierInfo);
	}
	
	public java.lang.String getSupplierInfo() {
		return getStr("supplier_info");
	}

	public void setPurchasingOrderDate(java.util.Date purchasingOrderDate) {
		set("purchasing_order_date", purchasingOrderDate);
	}
	
	public java.util.Date getPurchasingOrderDate() {
		return get("purchasing_order_date");
	}

	public void setPurchasingStopDate(java.util.Date purchasingStopDate) {
		set("purchasing_stop_date", purchasingStopDate);
	}
	
	public java.util.Date getPurchasingStopDate() {
		return get("purchasing_stop_date");
	}

	public void setStaffName(java.lang.String staffName) {
		set("staff_name", staffName);
	}
	
	public java.lang.String getStaffName() {
		return getStr("staff_name");
	}

	public void setSinglePerson(java.lang.String singlePerson) {
		set("single_person", singlePerson);
	}
	
	public java.lang.String getSinglePerson() {
		return getStr("single_person");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}
	
	public java.lang.Integer getTotal() {
		return getInt("total");
	}

}
