package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends JbootModel<M> implements IBean {

	public void setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
	}
	
	public java.lang.String getLoginName() {
		return getStr("login_name");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setLoginPassword(java.lang.String loginPassword) {
		set("login_password", loginPassword);
	}
	
	public java.lang.String getLoginPassword() {
		return getStr("login_password");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setUserTel(java.lang.String userTel) {
		set("user_tel", userTel);
	}
	
	public java.lang.String getUserTel() {
		return getStr("user_tel");
	}

	public void setUserOpenid(java.lang.String userOpenid) {
		set("user_openID", userOpenid);
	}
	
	public java.lang.String getUserOpenid() {
		return getStr("user_openID");
	}

	public void setJiaoseId(java.lang.String jiaoseId) {
		set("jiaose_id", jiaoseId);
	}
	
	public java.lang.String getJiaoseId() {
		return getStr("jiaose_id");
	}

	public void setJoinDate(java.util.Date joinDate) {
		set("join_date", joinDate);
	}
	
	public java.util.Date getJoinDate() {
		return get("join_date");
	}

	public void setBirthdayDate(java.util.Date birthdayDate) {
		set("birthday_date", birthdayDate);
	}
	
	public java.util.Date getBirthdayDate() {
		return get("birthday_date");
	}

	public void setContactAddress(java.lang.String contactAddress) {
		set("contact_address", contactAddress);
	}
	
	public java.lang.String getContactAddress() {
		return getStr("contact_address");
	}

	public void setStaffGoto(java.lang.String staffGoto) {
		set("staff_goto", staffGoto);
	}
	
	public java.lang.String getStaffGoto() {
		return getStr("staff_goto");
	}

}
