package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderAppendix<M extends BaseOrderAppendix<M>> extends JbootModel<M> implements IBean {

	public void setAppendixId(java.lang.String appendixId) {
		set("appendix_id", appendixId);
	}
	
	public java.lang.String getAppendixId() {
		return getStr("appendix_id");
	}

	public void setAppendixContent(byte[] appendixContent) {
		set("appendix_content", appendixContent);
	}
	
	public byte[] getAppendixContent() {
		return get("appendix_content");
	}

}
