package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStaffCategory<M extends BaseStaffCategory<M>> extends JbootModel<M> implements IBean {

	public void setStaffCategoryId(java.lang.String staffCategoryId) {
		set("staff_category_id", staffCategoryId);
	}
	
	public java.lang.String getStaffCategoryId() {
		return getStr("staff_category_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setStaffCategoryName(java.lang.String staffCategoryName) {
		set("staff_category_name", staffCategoryName);
	}
	
	public java.lang.String getStaffCategoryName() {
		return getStr("staff_category_name");
	}

	public void setStaffCategoryOptionUser(java.lang.String staffCategoryOptionUser) {
		set("staff_category_option_user", staffCategoryOptionUser);
	}
	
	public java.lang.String getStaffCategoryOptionUser() {
		return getStr("staff_category_option_user");
	}

	public void setStaffCategoryOptionDate(java.util.Date staffCategoryOptionDate) {
		set("staff_category_option_date", staffCategoryOptionDate);
	}
	
	public java.util.Date getStaffCategoryOptionDate() {
		return get("staff_category_option_date");
	}

	public void setStaffCategoryUpdateDate(java.util.Date staffCategoryUpdateDate) {
		set("staff_category_update_date", staffCategoryUpdateDate);
	}
	
	public java.util.Date getStaffCategoryUpdateDate() {
		return get("staff_category_update_date");
	}

}
