package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaregouseOut<M extends BaseWaregouseOut<M>> extends JbootModel<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setWaregouseId(java.lang.String waregouseId) {
		set("waregouse_id", waregouseId);
	}
	
	public java.lang.String getWaregouseId() {
		return getStr("waregouse_id");
	}

	public void setWaregouseName(java.lang.String waregouseName) {
		set("waregouse_name", waregouseName);
	}
	
	public java.lang.String getWaregouseName() {
		return getStr("waregouse_name");
	}

	public void setWaregouseOutDate(java.lang.String waregouseOutDate) {
		set("waregouse_out_date", waregouseOutDate);
	}
	
	public java.lang.String getWaregouseOutDate() {
		return getStr("waregouse_out_date");
	}

	public void setWaregouseOutCount(java.lang.Integer waregouseOutCount) {
		set("waregouse_out_count", waregouseOutCount);
	}
	
	public java.lang.Integer getWaregouseOutCount() {
		return getInt("waregouse_out_count");
	}

	public void setWaregouseOption(java.lang.String waregouseOption) {
		set("waregouse_option", waregouseOption);
	}
	
	public java.lang.String getWaregouseOption() {
		return getStr("waregouse_option");
	}

	public void setWaregouseNum(java.lang.String waregouseNum) {
		set("waregouse_num", waregouseNum);
	}
	
	public java.lang.String getWaregouseNum() {
		return getStr("waregouse_num");
	}

}
