package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaymentBill<M extends BasePaymentBill<M>> extends JbootModel<M> implements IBean {

	public void setPaymentId(java.lang.String paymentId) {
		set("payment_id", paymentId);
	}
	
	public java.lang.String getPaymentId() {
		return getStr("payment_id");
	}

	public void setPurchasingOrderId(java.lang.String purchasingOrderId) {
		set("purchasing_order_id", purchasingOrderId);
	}
	
	public java.lang.String getPurchasingOrderId() {
		return getStr("purchasing_order_id");
	}

	public void setWaregouseId(java.lang.String waregouseId) {
		set("waregouse_id", waregouseId);
	}
	
	public java.lang.String getWaregouseId() {
		return getStr("waregouse_id");
	}

	public void setInvoiceNumber(java.lang.Integer invoiceNumber) {
		set("invoice_number", invoiceNumber);
	}
	
	public java.lang.Integer getInvoiceNumber() {
		return getInt("invoice_number");
	}

	public void setFillInvoice(java.lang.String fillInvoice) {
		set("fill_invoice", fillInvoice);
	}
	
	public java.lang.String getFillInvoice() {
		return getStr("fill_invoice");
	}

	public void setArticleNumber(java.lang.String articleNumber) {
		set("article_number", articleNumber);
	}
	
	public java.lang.String getArticleNumber() {
		return getStr("article_number");
	}

	public void setTotal(java.math.BigDecimal total) {
		set("total", total);
	}
	
	public java.math.BigDecimal getTotal() {
		return get("total");
	}

	public void setUnitPrice(java.math.BigDecimal unitPrice) {
		set("unit_price", unitPrice);
	}
	
	public java.math.BigDecimal getUnitPrice() {
		return get("unit_price");
	}

	public void setPaymentDate(java.util.Date paymentDate) {
		set("payment_date", paymentDate);
	}
	
	public java.util.Date getPaymentDate() {
		return get("payment_date");
	}

	public void setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public void setLeadOfficial(java.lang.String leadOfficial) {
		set("lead_official", leadOfficial);
	}
	
	public java.lang.String getLeadOfficial() {
		return getStr("lead_official");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setWaregouseName(java.lang.String waregouseName) {
		set("waregouse_name", waregouseName);
	}
	
	public java.lang.String getWaregouseName() {
		return getStr("waregouse_name");
	}

}
