package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInstitutionCategory<M extends BaseInstitutionCategory<M>> extends JbootModel<M> implements IBean {

	public void setInstitutionCategoryId(java.lang.String institutionCategoryId) {
		set("institution_category_id", institutionCategoryId);
	}
	
	public java.lang.String getInstitutionCategoryId() {
		return getStr("institution_category_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setInstitutionCategoryName(java.lang.String institutionCategoryName) {
		set("institution_category_name", institutionCategoryName);
	}
	
	public java.lang.String getInstitutionCategoryName() {
		return getStr("institution_category_name");
	}

	public void setInstitutionCategoryOptionUser(java.lang.String institutionCategoryOptionUser) {
		set("institution_category_option_user", institutionCategoryOptionUser);
	}
	
	public java.lang.String getInstitutionCategoryOptionUser() {
		return getStr("institution_category_option_user");
	}

	public void setInstitutionCategoryOptionDate(java.util.Date institutionCategoryOptionDate) {
		set("institution_category_option_date", institutionCategoryOptionDate);
	}
	
	public java.util.Date getInstitutionCategoryOptionDate() {
		return get("institution_category_option_date");
	}

	public void setInstitutionCategoryUpdateDate(java.util.Date institutionCategoryUpdateDate) {
		set("institution_category_update_date", institutionCategoryUpdateDate);
	}
	
	public java.util.Date getInstitutionCategoryUpdateDate() {
		return get("institution_category_update_date");
	}

}
