package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRepairOrder<M extends BaseRepairOrder<M>> extends JbootModel<M> implements IBean {

	public void setRepairOrderId(java.lang.String repairOrderId) {
		set("repair_order_id", repairOrderId);
	}
	
	public java.lang.String getRepairOrderId() {
		return getStr("repair_order_id");
	}

	public void setAppendixId(java.lang.String appendixId) {
		set("appendix_id", appendixId);
	}
	
	public java.lang.String getAppendixId() {
		return getStr("appendix_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setRepairOrderName(java.lang.String repairOrderName) {
		set("repair_order_name", repairOrderName);
	}
	
	public java.lang.String getRepairOrderName() {
		return getStr("repair_order_name");
	}

	public void setRepairInstitution(java.lang.String repairInstitution) {
		set("repair_institution", repairInstitution);
	}
	
	public java.lang.String getRepairInstitution() {
		return getStr("repair_institution");
	}

	public void setRepairWangdian(java.lang.String repairWangdian) {
		set("repair_wangdian", repairWangdian);
	}
	
	public java.lang.String getRepairWangdian() {
		return getStr("repair_wangdian");
	}

	public void setRepairJiaOfficial(java.lang.String repairJiaOfficial) {
		set("repair_jia_official", repairJiaOfficial);
	}
	
	public java.lang.String getRepairJiaOfficial() {
		return getStr("repair_jia_official");
	}

	public void setRepairXiadanDate(java.util.Date repairXiadanDate) {
		set("repair_xiadan_date", repairXiadanDate);
	}
	
	public java.util.Date getRepairXiadanDate() {
		return get("repair_xiadan_date");
	}

	public void setRepairXiadanType(java.lang.String repairXiadanType) {
		set("repair_xiadan_type", repairXiadanType);
	}
	
	public java.lang.String getRepairXiadanType() {
		return getStr("repair_xiadan_type");
	}

	public void setRepairCost(java.lang.String repairCost) {
		set("repair_cost", repairCost);
	}
	
	public java.lang.String getRepairCost() {
		return getStr("repair_cost");
	}

	public void setRepairPaiqian(java.lang.String repairPaiqian) {
		set("repair_paiqian", repairPaiqian);
	}
	
	public java.lang.String getRepairPaiqian() {
		return getStr("repair_paiqian");
	}

	public void setRepairFinshDate(java.util.Date repairFinshDate) {
		set("repair_finsh_date", repairFinshDate);
	}
	
	public java.util.Date getRepairFinshDate() {
		return get("repair_finsh_date");
	}

	public void setRepairStatus(java.lang.String repairStatus) {
		set("repair_status", repairStatus);
	}
	
	public java.lang.String getRepairStatus() {
		return getStr("repair_status");
	}

}
