package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaregouseCategory<M extends BaseWaregouseCategory<M>> extends JbootModel<M> implements IBean {

	public void setWaregouseCategoryId(java.lang.String waregouseCategoryId) {
		set("waregouse_category_id", waregouseCategoryId);
	}
	
	public java.lang.String getWaregouseCategoryId() {
		return getStr("waregouse_category_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setWaregouseCategoryName(java.lang.String waregouseCategoryName) {
		set("waregouse_category_name", waregouseCategoryName);
	}
	
	public java.lang.String getWaregouseCategoryName() {
		return getStr("waregouse_category_name");
	}

	public void setWaregouseCategoryOptionUser(java.lang.String waregouseCategoryOptionUser) {
		set("waregouse_category_option_user", waregouseCategoryOptionUser);
	}
	
	public java.lang.String getWaregouseCategoryOptionUser() {
		return getStr("waregouse_category_option_user");
	}

	public void setWaregouseCategoryOptionDate(java.util.Date waregouseCategoryOptionDate) {
		set("waregouse_category_option_date", waregouseCategoryOptionDate);
	}
	
	public java.util.Date getWaregouseCategoryOptionDate() {
		return get("waregouse_category_option_date");
	}

	public void setWaregouseCategoryUpdateDate(java.util.Date waregouseCategoryUpdateDate) {
		set("waregouse_category_update_date", waregouseCategoryUpdateDate);
	}
	
	public java.util.Date getWaregouseCategoryUpdateDate() {
		return get("waregouse_category_update_date");
	}

}
