package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInstitutionInfo<M extends BaseInstitutionInfo<M>> extends JbootModel<M> implements IBean {

	public void setInstitutionId(java.lang.String institutionId) {
		set("institution_id", institutionId);
	}
	
	public java.lang.String getInstitutionId() {
		return getStr("institution_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setInstitutionCategoryId(java.lang.String institutionCategoryId) {
		set("institution_category_id", institutionCategoryId);
	}
	
	public java.lang.String getInstitutionCategoryId() {
		return getStr("institution_category_id");
	}

	public void setInstitutionName(java.lang.String institutionName) {
		set("institution_name", institutionName);
	}
	
	public java.lang.String getInstitutionName() {
		return getStr("institution_name");
	}

	public void setInstitutionCategory(java.lang.String institutionCategory) {
		set("institution_category", institutionCategory);
	}
	
	public java.lang.String getInstitutionCategory() {
		return getStr("institution_category");
	}

	public void setInstitutionStatus(java.lang.String institutionStatus) {
		set("institution_status", institutionStatus);
	}
	
	public java.lang.String getInstitutionStatus() {
		return getStr("institution_status");
	}

	public void setInstitutionOfficial(java.lang.String institutionOfficial) {
		set("institution_official", institutionOfficial);
	}
	
	public java.lang.String getInstitutionOfficial() {
		return getStr("institution_official");
	}

	public void setInstitutionContcts(java.lang.String institutionContcts) {
		set("institution_contcts", institutionContcts);
	}
	
	public java.lang.String getInstitutionContcts() {
		return getStr("institution_contcts");
	}

	public void setInstitutionAddress(java.lang.String institutionAddress) {
		set("institution_address", institutionAddress);
	}
	
	public java.lang.String getInstitutionAddress() {
		return getStr("institution_address");
	}

	public void setInstitutionTel(java.lang.String institutionTel) {
		set("institution_tel", institutionTel);
	}
	
	public java.lang.String getInstitutionTel() {
		return getStr("institution_tel");
	}

	public void setInstitutionWangdian(java.lang.String institutionWangdian) {
		set("institution_wangdian", institutionWangdian);
	}
	
	public java.lang.String getInstitutionWangdian() {
		return getStr("institution_wangdian");
	}

}
